# air configuration file
root = "."
tmp_dir = "tmp"

[build]
pre_cmd = ["npm run build:embed --prefix web"]
cmd = "go build -o ./tmp/main main.go"
bin = "tmp/main"
include_ext = ["go", "json", "html", "js", "css", "env", "ts", "tsx"]
include_dir = ["internal", "cmd", "assets", "web"]
include_file = ["main.go"]
exclude_dir = ["tmp", "vendor", "data", "logs", ".git", "web/node_modules", "web/dist", "internal/infrastructure/frontend/build"]
exclude_regex = ["_test\\.go$"]
poll = true
poll_interval = 200
delay = 500
stop_on_error = false
send_interrupt = true
kill_delay = 500
rerun = true
rerun_delay = 500

[log]
time = true
main_only = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
